data:
#  data_location: /root/buckets/pratik-ddsp2-data/monophonic-4secchunks # local
  data_location: /work/gk77/k77021/data/timbre/monophonic-4secchunks #wisteria
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 44100
  signal_length: &signallength 176400
  block_size: &blocksize 441 # must be a power of 2 if using realtime

  oneshot: false # crop every audio file to exactly signal length
  out_dir: ./preprocessed/

model:
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75
  load_checkpoint: false
  eval_per_n_epochs: 200